In [10]:
%pip install pandas numpy matplotlib seaborn scikit-learn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Cargar el dataset
df = pd.read_csv('OnlineNewsPopularity.csv')

# 2. Limpiar espacios en blanco en los nombres de las columnas
df.columns = [col.strip() for col in df.columns]

# 3. Eliminar columnas no predictivas
df_clean = df.drop(['url', 'timedelta'], axis=1)

print(f"Dataset cargado con éxito.")
print(f"Filas: {df_clean.shape[0]} | Columnas: {df_clean.shape[1]}")

[notice] A new release of pip is available: 23.2.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (3.0.2)
Requirement already satisfied: numpy in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (2.4.4)
Requirement already satisfied: matplotlib in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yarel\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\yarel\appdata\roaming\python\python311\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\yarel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\yarel\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Dataset cargado con éxito.
Filas: 39644 | Columnas: 59

In [11]:
# 4. Revisar información general
print(df_clean.info())

# 5. Revisar valores faltantes
print("\nValores faltantes por columna:")
print(df_clean.isnull().sum().sort_values(ascending=False))

# 6. Revisar duplicados
print("\nFilas duplicadas:", df_clean.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 39644 entries, 0 to 39643
Data columns (total 59 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   n_tokens_title                 39644 non-null  float64
 1   n_tokens_content               39644 non-null  float64
 2   n_unique_tokens                39644 non-null  float64
 3   n_non_stop_words               39644 non-null  float64
 4   n_non_stop_unique_tokens       39644 non-null  float64
 5   num_hrefs                      39644 non-null  float64
 6   num_self_hrefs                 39644 non-null  float64
 7   num_imgs                       39644 non-null  float64
 8   num_videos                     39644 non-null  float64
 9   average_token_length           39644 non-null  float64
 10  num_keywords                   39644 non-null  float64
 11  data_channel_is_lifestyle      39644 non-null  float64
 12  data_channel_is_entertainment  39644 non-null  float64
 13  data_channel_is_bus            39644 non-null  float64
 14  data_channel_is_socmed         39644 non-null  float64
 15  data_channel_is_tech           39644 non-null  float64
 16  data_channel_is_world          39644 non-null  float64
 17  kw_min_min                     39644 non-null  float64
 18  kw_max_min                     39644 non-null  float64
 19  kw_avg_min                     39644 non-null  float64
 20  kw_min_max                     39644 non-null  float64
 21  kw_max_max                     39644 non-null  float64
 22  kw_avg_max                     39644 non-null  float64
 23  kw_min_avg                     39644 non-null  float64
 24  kw_max_avg                     39644 non-null  float64
 25  kw_avg_avg                     39644 non-null  float64
 26  self_reference_min_shares      39644 non-null  float64
 27  self_reference_max_shares      39644 non-null  float64
 28  self_reference_avg_sharess     39644 non-null  float64
 29  weekday_is_monday              39644 non-null  float64
 30  weekday_is_tuesday             39644 non-null  float64
 31  weekday_is_wednesday           39644 non-null  float64
 32  weekday_is_thursday            39644 non-null  float64
 33  weekday_is_friday              39644 non-null  float64
 34  weekday_is_saturday            39644 non-null  float64
 35  weekday_is_sunday              39644 non-null  float64
 36  is_weekend                     39644 non-null  float64
 37  LDA_00                         39644 non-null  float64
 38  LDA_01                         39644 non-null  float64
 39  LDA_02                         39644 non-null  float64
 40  LDA_03                         39644 non-null  float64
 41  LDA_04                         39644 non-null  float64
 42  global_subjectivity            39644 non-null  float64
 43  global_sentiment_polarity      39644 non-null  float64
 44  global_rate_positive_words     39644 non-null  float64
 45  global_rate_negative_words     39644 non-null  float64
 46  rate_positive_words            39644 non-null  float64
 47  rate_negative_words            39644 non-null  float64
 48  avg_positive_polarity          39644 non-null  float64
 49  min_positive_polarity          39644 non-null  float64
 50  max_positive_polarity          39644 non-null  float64
 51  avg_negative_polarity          39644 non-null  float64
 52  min_negative_polarity          39644 non-null  float64
 53  max_negative_polarity          39644 non-null  float64
 54  title_subjectivity             39644 non-null  float64
 55  title_sentiment_polarity       39644 non-null  float64
 56  abs_title_subjectivity         39644 non-null  float64
 57  abs_title_sentiment_polarity   39644 non-null  float64
 58  shares                         39644 non-null  int64
dtypes: float64(58), int64(1)
memory usage: 17.8 MB
None

Valores faltantes por columna:
n_tokens_title                   0
n_tokens_content                 0
n_unique_tokens                  0
n_non_stop_words                 0
n_non_stop_unique_tokens         0
num_hrefs                        0
num_self_hrefs                   0
num_imgs                         0
num_videos                       0
average_token_length             0
num_keywords                     0
data_channel_is_lifestyle        0
data_channel_is_entertainment    0
data_channel_is_bus              0
data_channel_is_socmed           0
data_channel_is_tech             0
data_channel_is_world            0
kw_min_min                       0
kw_max_min                       0
kw_avg_min                       0
kw_min_max                       0
kw_max_max                       0
kw_avg_max                       0
kw_min_avg                       0
kw_max_avg                       0
kw_avg_avg                       0
self_reference_min_shares        0
self_reference_max_shares        0
self_reference_avg_sharess       0
weekday_is_monday                0
weekday_is_tuesday               0
weekday_is_wednesday             0
weekday_is_thursday              0
weekday_is_friday                0
weekday_is_saturday              0
weekday_is_sunday                0
is_weekend                       0
LDA_00                           0
LDA_01                           0
LDA_02                           0
LDA_03                           0
LDA_04                           0
global_subjectivity              0
global_sentiment_polarity        0
global_rate_positive_words       0
global_rate_negative_words       0
rate_positive_words              0
rate_negative_words              0
avg_positive_polarity            0
min_positive_polarity            0
max_positive_polarity            0
avg_negative_polarity            0
min_negative_polarity            0
max_negative_polarity            0
title_subjectivity               0
title_sentiment_polarity         0
abs_title_subjectivity           0
abs_title_sentiment_polarity     0
shares                           0
dtype: int64

Filas duplicadas: 0

In [12]:
# 7. Estadísticas descriptivas
df_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
n_tokens_title,39644.0,10.398749,2.114037,2.00000,9.000000,10.000000,12.000000,23.000000
n_tokens_content,39644.0,546.514731,471.107508,0.00000,246.000000,409.000000,716.000000,8474.000000
n_unique_tokens,39644.0,0.548216,3.520708,0.00000,0.470870,0.539226,0.608696,701.000000
n_non_stop_words,39644.0,0.996469,5.231231,0.00000,1.000000,1.000000,1.000000,1042.000000
n_non_stop_unique_tokens,39644.0,0.689175,3.264816,0.00000,0.625739,0.690476,0.754630,650.000000
num_hrefs,39644.0,10.883690,11.332017,0.00000,4.000000,8.000000,14.000000,304.000000
num_self_hrefs,39644.0,3.293638,3.855141,0.00000,1.000000,3.000000,4.000000,116.000000
num_imgs,39644.0,4.544143,8.309434,0.00000,1.000000,1.000000,4.000000,128.000000
num_videos,39644.0,1.249874,4.107855,0.00000,0.000000,0.000000,1.000000,91.000000
average_token_length,39644.0,4.548239,0.844406,0.00000,4.478404,4.664082,4.854839,8.041534
num_keywords,39644.0,7.223767,1.909130,1.00000,6.000000,7.000000,9.000000,10.000000
data_channel_is_lifestyle,39644.0,0.052946,0.223929,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_entertainment,39644.0,0.178009,0.382525,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_bus,39644.0,0.157855,0.364610,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_socmed,39644.0,0.058597,0.234871,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_tech,39644.0,0.185299,0.388545,0.00000,0.000000,0.000000,0.000000,1.000000
data_channel_is_world,39644.0,0.212567,0.409129,0.00000,0.000000,0.000000,0.000000,1.000000
kw_min_min,39644.0,26.106801,69.633215,-1.00000,-1.000000,-1.000000,4.000000,377.000000
kw_max_min,39644.0,1153.951682,3857.990877,0.00000,445.000000,660.000000,1000.000000,298400.000000
kw_avg_min,39644.0,312.366967,620.783887,-1.00000,141.750000,235.500000,357.000000,42827.857143
kw_min_max,39644.0,13612.354102,57986.029357,0.00000,0.000000,1400.000000,7900.000000,843300.000000
kw_max_max,39644.0,752324.066694,214502.129573,0.00000,843300.000000,843300.000000,843300.000000,843300.000000
kw_avg_max,39644.0,259281.938083,135102.247285,0.00000,172846.875000,244572.222223,330980.000000,843300.000000
kw_min_avg,39644.0,1117.146610,1137.456951,-1.00000,0.000000,1023.635611,2056.781032,3613.039819
kw_max_avg,39644.0,5657.211151,6098.871957,0.00000,3562.101631,4355.688836,6019.953968,298400.000000
kw_avg_avg,39644.0,3135.858639,1318.150397,0.00000,2382.448566,2870.074878,3600.229564,43567.659946
self_reference_min_shares,39644.0,3998.755396,19738.670516,0.00000,639.000000,1200.000000,2600.000000,843300.000000
self_reference_max_shares,39644.0,10329.212662,41027.576613,0.00000,1100.000000,2800.000000,8000.000000,843300.000000
self_reference_avg_sharess,39644.0,6401.697580,24211.332231,0.00000,981.187500,2200.000000,5200.000000,843300.000000
weekday_is_monday,39644.0,0.168020,0.373889,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_tuesday,39644.0,0.186409,0.389441,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_wednesday,39644.0,0.187544,0.390353,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_thursday,39644.0,0.183306,0.386922,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_friday,39644.0,0.143805,0.350896,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_saturday,39644.0,0.061876,0.240933,0.00000,0.000000,0.000000,0.000000,1.000000
weekday_is_sunday,39644.0,0.069039,0.253524,0.00000,0.000000,0.000000,0.000000,1.000000
is_weekend,39644.0,0.130915,0.337312,0.00000,0.000000,0.000000,0.000000,1.000000
LDA_00,39644.0,0.184599,0.262975,0.00000,0.025051,0.033387,0.240958,0.926994
LDA_01,39644.0,0.141256,0.219707,0.00000,0.025012,0.033345,0.150831,0.925947
LDA_02,39644.0,0.216321,0.282145,0.00000,0.028571,0.040004,0.334218,0.919999
LDA_03,39644.0,0.223770,0.295191,0.00000,0.028571,0.040001,0.375763,0.926534
LDA_04,39644.0,0.234029,0.289183,0.00000,0.028574,0.040727,0.399986,0.927191
global_subjectivity,39644.0,0.443370,0.116685,0.00000,0.396167,0.453457,0.508333,1.000000
global_sentiment_polarity,39644.0,0.119309,0.096931,-0.39375,0.057757,0.119117,0.177832,0.727841
global_rate_positive_words,39644.0,0.039625,0.017429,0.00000,0.028384,0.039023,0.050279,0.155488
global_rate_negative_words,39644.0,0.016612,0.010828,0.00000,0.009615,0.015337,0.021739,0.184932
rate_positive_words,39644.0,0.682150,0.190206,0.00000,0.600000,0.710526,0.800000,1.000000
rate_negative_words,39644.0,0.287934,0.156156,0.00000,0.185185,0.280000,0.384615,1.000000
avg_positive_polarity,39644.0,0.353825,0.104542,0.00000,0.306244,0.358755,0.411428,1.000000
min_positive_polarity,39644.0,0.095446,0.071315,0.00000,0.050000,0.100000,0.100000,1.000000
max_positive_polarity,39644.0,0.756728,0.247786,0.00000,0.600000,0.800000,1.000000,1.000000
avg_negative_polarity,39644.0,-0.259524,0.127726,-1.00000,-0.328383,-0.253333,-0.186905,0.000000
min_negative_polarity,39644.0,-0.521944,0.290290,-1.00000,-0.700000,-0.500000,-0.300000,0.000000
max_negative_polarity,39644.0,-0.107500,0.095373,-1.00000,-0.125000,-0.100000,-0.050000,0.000000
title_subjectivity,39644.0,0.282353,0.324247,0.00000,0.000000,0.150000,0.500000,1.000000
title_sentiment_polarity,39644.0,0.071425,0.265450,-1.00000,0.000000,0.000000,0.150000,1.000000
abs_title_subjectivity,39644.0,0.341843,0.188791,0.00000,0.166667,0.500000,0.500000,0.500000
abs_title_sentiment_polarity,39644.0,0.156064,0.226294,0.00000,0.000000,0.000000,0.250000,1.000000
shares,39644.0,3395.380184,11626.950749,1.00000,946.000000,1400.000000,2800.000000,843300.000000

In [13]:
# Separar variable objetivo
X = df_clean.drop('shares', axis=1)
y = df_clean['shares']

print("X:", X.shape)
print("y:", y.shape)

X: (39644, 58)
y: (39644,)

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print("Datos escalados:", X_scaled.shape)

Datos escalados: (39644, 58)

esta parte correcto

In [15]:
import pandas as pd

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled_df.describe().T

,count,mean,std,min,25%,50%,75%,max
n_tokens_title,39644.0,4.129479e-16,1.000013,-3.972899,-0.661657,-0.188622,0.757447,5.960828
n_tokens_content,39644.0,7.456003e-17,1.000013,-1.160078,-0.637898,-0.291900,0.359764,16.827550
n_unique_tokens,39644.0,-1.218770e-17,1.000013,-0.155714,-0.021969,-0.002554,0.017179,198.954458
n_non_stop_words,39644.0,-8.065388e-19,1.000013,-0.190487,0.000675,0.000675,0.000675,199.000326
n_non_stop_unique_tokens,39644.0,1.953616e-17,1.000013,-0.211094,-0.019430,0.000398,0.020049,198.883779
num_hrefs,39644.0,8.459696e-17,1.000013,-0.960449,-0.607463,-0.254476,0.275004,25.866534
num_self_hrefs,39644.0,-1.147077e-17,1.000013,-0.854360,-0.594963,-0.076169,0.183228,29.235709
num_imgs,39644.0,-2.007385e-17,1.000013,-0.546872,-0.426526,-0.426526,-0.065486,14.857501
num_videos,39644.0,1.613078e-18,1.000013,-0.304268,-0.304268,-0.304268,-0.060829,21.848691
average_token_length,39644.0,1.376493e-16,1.000013,-5.386389,-0.082705,0.137190,0.363100,4.137038
num_keywords,39644.0,1.376493e-16,1.000013,-3.260042,-0.641015,-0.117210,0.930401,1.454206
data_channel_is_lifestyle,39644.0,-3.728001e-17,1.000013,-0.236445,-0.236445,-0.236445,-0.236445,4.229313
data_channel_is_entertainment,39644.0,0.000000e+00,1.000013,-0.465359,-0.465359,-0.465359,-0.465359,2.148880
data_channel_is_bus,39644.0,-3.441232e-17,1.000013,-0.432948,-0.432948,-0.432948,-0.432948,2.309747
data_channel_is_socmed,39644.0,-1.147077e-17,1.000013,-0.249487,-0.249487,-0.249487,-0.249487,4.008224
data_channel_is_tech,39644.0,6.882464e-17,1.000013,-0.476911,-0.476911,-0.476911,-0.476911,2.096826
data_channel_is_world,39644.0,4.588309e-17,1.000013,-0.519566,-0.519566,-0.519566,-0.519566,1.924682
kw_min_min,39644.0,6.882464e-17,1.000013,-0.389285,-0.389285,-0.389285,-0.317479,5.039228
kw_max_min,39644.0,5.448617e-17,1.000013,-0.299111,-0.183764,-0.128035,-0.039905,77.047823
kw_avg_min,39644.0,-4.588309e-17,1.000013,-0.504799,-0.274845,-0.123824,0.071899,68.487645
kw_min_max,39644.0,-1.147077e-17,1.000013,-0.234755,-0.234755,-0.210611,-0.098514,14.308586
kw_max_max,39644.0,1.835324e-16,1.000013,-3.507348,0.424131,0.424131,0.424131,0.424131
kw_avg_max,39644.0,1.605908e-16,1.000013,-1.919178,-0.639783,-0.108880,0.530702,4.322840
kw_min_avg,39644.0,-5.735387e-17,1.000013,-0.983036,-0.982156,-0.082212,0.826094,2.194303
kw_max_avg,39644.0,-4.875079e-17,1.000013,-0.927595,-0.343528,-0.213406,0.059478,48.000103
kw_avg_avg,39644.0,-3.441232e-17,1.000013,-2.379014,-0.571573,-0.201636,0.352294,30.673519
self_reference_min_shares,39644.0,3.728001e-17,1.000013,-0.202587,-0.170214,-0.141792,-0.070865,42.521194
self_reference_max_shares,39644.0,2.867693e-18,1.000013,-0.251766,-0.224954,-0.183518,-0.056773,20.302961
self_reference_avg_sharess,39644.0,-1.864001e-17,1.000013,-0.264412,-0.223886,-0.173545,-0.049634,34.566824
weekday_is_monday,39644.0,3.638386e-17,1.000013,-0.449391,-0.449391,-0.449391,-0.449391,2.225232
weekday_is_tuesday,39644.0,4.713771e-17,1.000013,-0.478664,-0.478664,-0.478664,-0.478664,2.089150
weekday_is_wednesday,39644.0,5.018463e-17,1.000013,-0.480454,-0.480454,-0.480454,-0.480454,2.081364
weekday_is_thursday,39644.0,2.939386e-17,1.000013,-0.473761,-0.473761,-0.473761,-0.473761,2.110769
weekday_is_friday,39644.0,-3.477078e-17,1.000013,-0.409827,-0.409827,-0.409827,-0.409827,2.440055
weekday_is_saturday,39644.0,-4.373232e-17,1.000013,-0.256821,-0.256821,-0.256821,-0.256821,3.893769
weekday_is_sunday,39644.0,-5.018463e-18,1.000013,-0.272322,-0.272322,-0.272322,-0.272322,3.672121
is_weekend,39644.0,-6.380618e-17,1.000013,-0.388118,-0.388118,-0.388118,-0.388118,2.576536
LDA_00,39644.0,0.000000e+00,1.000013,-0.701974,-0.606714,-0.575012,0.214316,2.823103
LDA_01,39644.0,-3.369540e-17,1.000013,-0.642935,-0.529089,-0.491163,0.043584,3.571575
LDA_02,39644.0,1.720616e-16,1.000013,-0.766711,-0.665444,-0.624924,0.417864,2.494060
LDA_03,39644.0,-1.476862e-16,1.000013,-0.758061,-0.661269,-0.622551,0.514904,2.380742
LDA_04,39644.0,8.603080e-17,1.000013,-0.809287,-0.710477,-0.668449,0.573887,2.396991
global_subjectivity,39644.0,1.835324e-16,1.000013,-3.799778,-0.404544,0.086449,0.556748,4.770438
global_sentiment_polarity,39644.0,0.000000e+00,1.000013,-5.293121,-0.635018,-0.001986,0.603769,6.278089
global_rate_positive_words,39644.0,4.588309e-17,1.000013,-2.273573,-0.644955,-0.034544,0.611328,6.647926
global_rate_negative_words,39644.0,8.603080e-17,1.000013,-1.534231,-0.646191,-0.117726,0.473511,15.545321
rate_positive_words,39644.0,2.064739e-16,1.000013,-3.586415,-0.431906,0.149188,0.619597,1.671100
rate_negative_words,39644.0,8.603080e-17,1.000013,-1.843908,-0.657994,-0.050806,0.619145,4.560030
avg_positive_polarity,39644.0,1.147077e-16,1.000013,-3.384561,-0.455146,0.047161,0.551008,6.181076
min_positive_polarity,39644.0,-1.147077e-17,1.000013,-1.338384,-0.637259,0.063865,0.063865,12.684102
max_positive_polarity,39644.0,-1.777970e-16,1.000013,-3.053998,-0.632520,0.174639,0.981798,0.981798
avg_negative_polarity,39644.0,5.018463e-17,1.000013,-5.797463,-0.539119,0.048470,0.568564,2.031912
min_negative_polarity,39644.0,2.294155e-17,1.000013,-1.646847,-0.613383,0.075594,0.764570,1.798034
max_negative_polarity,39644.0,1.147077e-16,1.000013,-9.358111,-0.183490,0.078642,0.602906,1.127170
title_subjectivity,39644.0,-6.954157e-17,1.000013,-0.870807,-0.870807,-0.408191,0.671245,2.213297
title_sentiment_polarity,39644.0,-1.147077e-17,1.000013,-4.036308,-0.269076,-0.269076,0.296009,3.498156
abs_title_subjectivity,39644.0,-5.520310e-17,1.000013,-1.810719,-0.927896,0.837749,0.837749,0.837749
abs_title_sentiment_polarity,39644.0,5.018463e-17,1.000013,-0.689658,-0.689658,-0.689658,0.415112,3.729424

PRUEBAAA

In [16]:
//prueba

SyntaxError: invalid syntax (1009679106.py, line 1)

In [17]:
from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings('ignore')

# Guardamos los resultados de cada iteración
resultados_kmeans = {}

In [18]:
k = 2
km = KMeans(n_clusters=k, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

# Distribución de grupos
distribucion = pd.Series(labels).value_counts().sort_index()

resultados_kmeans[k] = labels
print(f"K-Means con K={k}")
print(f"Distribución de grupos:")
for grupo, cantidad in distribucion.items():
    print(f"  G{grupo+1}: {cantidad} artículos")
print(f"  Total: {len(labels)}")

K-Means con K=2
Distribución de grupos:
  G1: 38458 artículos
  G2: 1186 artículos
  Total: 39644

In [19]:
k = 3
km = KMeans(n_clusters=k, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

distribucion = pd.Series(labels).value_counts().sort_index()

resultados_kmeans[k] = labels
print(f"K-Means con K={k}")
print(f"Distribución de grupos:")
for grupo, cantidad in distribucion.items():
    print(f"  G{grupo+1}: {cantidad} artículos")
print(f"  Total: {len(labels)}")

K-Means con K=3
Distribución de grupos:
  G1: 12651 artículos
  G2: 17688 artículos
  G3: 9305 artículos
  Total: 39644

In [20]:
k = 4
km = KMeans(n_clusters=k, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

distribucion = pd.Series(labels).value_counts().sort_index()

resultados_kmeans[k] = labels
print(f"K-Means con K={k}")
print(f"Distribución de grupos:")
for grupo, cantidad in distribucion.items():
    print(f"  G{grupo+1}: {cantidad} artículos")
print(f"  Total: {len(labels)}")

K-Means con K=4
Distribución de grupos:
  G1: 13375 artículos
  G2: 25083 artículos
  G3: 1 artículos
  G4: 1185 artículos
  Total: 39644

In [21]:
k = 5
km = KMeans(n_clusters=k, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

distribucion = pd.Series(labels).value_counts().sort_index()

resultados_kmeans[k] = labels
print(f"K-Means con K={k}")
print(f"Distribución de grupos:")
for grupo, cantidad in distribucion.items():
    print(f"  G{grupo+1}: {cantidad} artículos")
print(f"  Total: {len(labels)}")

K-Means con K=5
Distribución de grupos:
  G1: 1184 artículos
  G2: 12687 artículos
  G3: 8215 artículos
  G4: 17557 artículos
  G5: 1 artículos
  Total: 39644

In [22]:
k = 6
km = KMeans(n_clusters=k, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

distribucion = pd.Series(labels).value_counts().sort_index()

resultados_kmeans[k] = labels
print(f"K-Means con K={k}")
print(f"Distribución de grupos:")
for grupo, cantidad in distribucion.items():
    print(f"  G{grupo+1}: {cantidad} artículos")
print(f"  Total: {len(labels)}")

K-Means con K=6
Distribución de grupos:
  G1: 9195 artículos
  G2: 7981 artículos
  G3: 8203 artículos
  G4: 1 artículos
  G5: 1185 artículos
  G6: 13079 artículos
  Total: 39644

In [23]:
k = 7
km = KMeans(n_clusters=k, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

distribucion = pd.Series(labels).value_counts().sort_index()

resultados_kmeans[k] = labels
print(f"K-Means con K={k}")
print(f"Distribución de grupos:")
for grupo, cantidad in distribucion.items():
    print(f"  G{grupo+1}: {cantidad} artículos")
print(f"  Total: {len(labels)}")

K-Means con K=7
Distribución de grupos:
  G1: 7888 artículos
  G2: 1185 artículos
  G3: 7749 artículos
  G4: 3809 artículos
  G5: 7086 artículos
  G6: 1 artículos
  G7: 11926 artículos
  Total: 39644

In [24]:
k = 8
km = KMeans(n_clusters=k, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

distribucion = pd.Series(labels).value_counts().sort_index()

resultados_kmeans[k] = labels
print(f"K-Means con K={k}")
print(f"Distribución de grupos:")
for grupo, cantidad in distribucion.items():
    print(f"  G{grupo+1}: {cantidad} artículos")
print(f"  Total: {len(labels)}")

K-Means con K=8
Distribución de grupos:
  G1: 6998 artículos
  G2: 7802 artículos
  G3: 3681 artículos
  G4: 7709 artículos
  G5: 1184 artículos
  G6: 1 artículos
  G7: 6355 artículos
  G8: 5914 artículos
  Total: 39644

In [25]:
k = 9
km = KMeans(n_clusters=k, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

distribucion = pd.Series(labels).value_counts().sort_index()

resultados_kmeans[k] = labels
print(f"K-Means con K={k}")
print(f"Distribución de grupos:")
for grupo, cantidad in distribucion.items():
    print(f"  G{grupo+1}: {cantidad} artículos")
print(f"  Total: {len(labels)}")

K-Means con K=9
Distribución de grupos:
  G1: 2529 artículos
  G2: 7211 artículos
  G3: 163 artículos
  G4: 10838 artículos
  G5: 1185 artículos
  G6: 7390 artículos
  G7: 1 artículos
  G8: 6703 artículos
  G9: 3624 artículos
  Total: 39644

In [26]:
from sklearn.cluster import DBSCAN
import time

# Prueba con UNA combinación para estimar tiempo
start = time.time()
db_test = DBSCAN(eps=0.5, min_samples=5)
db_test.fit(X_scaled)
end = time.time()

n_clusters = len(set(db_test.labels_)) - (1 if -1 in db_test.labels_ else 0)
n_ruido = list(db_test.labels_).count(-1)

print(f"Tiempo por iteración: {end-start:.2f} segundos")
print(f"Tiempo estimado para 400 iteraciones: {((end-start)*400)/60:.1f} minutos")
print(f"Clusters encontrados: {n_clusters}")
print(f"Puntos de ruido: {n_ruido}")

Tiempo por iteración: 3.58 segundos
Tiempo estimado para 400 iteraciones: 23.9 minutos
Clusters encontrados: 0
Puntos de ruido: 39644

In [27]:
from sklearn.cluster import DBSCAN
import pandas as pd
import time

# Diccionario para guardar todos los resultados
resultados_dbscan = {}
iteracion = 1

In [28]:
# Ejemplo iteración 1: eps=0.25, min_samples=3
k_eps = 0.25
k_min = 3

start = time.time()
db = DBSCAN(eps=k_eps, min_samples=k_min)
labels = db.fit_predict(X_scaled)
end = time.time()

n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_ruido = list(labels).count(-1)
distribucion = pd.Series(labels).value_counts().sort_index()

resultados_dbscan[(k_eps, k_min)] = labels

print(f"Iteración | eps={k_eps} | MinPts={k_min}")
print(f"Clusters encontrados: {n_clusters}")
print(f"Puntos de ruido: {n_ruido} ({n_ruido/len(labels)*100:.1f}%)")
print(f"Tiempo: {end-start:.2f}s")
print(f"Distribución:")
for grupo, cantidad in distribucion.items():
    nombre = "Ruido" if grupo == -1 else f"G{grupo+1}"
    print(f"  {nombre}: {cantidad}")

Iteración | eps=0.25 | MinPts=3
Clusters encontrados: 0
Puntos de ruido: 39644 (100.0%)
Tiempo: 3.45s
Distribución:
  Ruido: 39644

In [29]:
# Ejemplo iteración 1: eps=0.25, min_samples=3
k_eps = 0.5
k_min = 7

start = time.time()
db = DBSCAN(eps=k_eps, min_samples=k_min)
labels = db.fit_predict(X_scaled)
end = time.time()

n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_ruido = list(labels).count(-1)
distribucion = pd.Series(labels).value_counts().sort_index()

resultados_dbscan[(k_eps, k_min)] = labels

print(f"Iteración | eps={k_eps} | MinPts={k_min}")
print(f"Clusters encontrados: {n_clusters}")
print(f"Puntos de ruido: {n_ruido} ({n_ruido/len(labels)*100:.1f}%)")
print(f"Tiempo: {end-start:.2f}s")
print(f"Distribución:")
for grupo, cantidad in distribucion.items():
    nombre = "Ruido" if grupo == -1 else f"G{grupo+1}"
    print(f"  {nombre}: {cantidad}")

Iteración | eps=0.5 | MinPts=7
Clusters encontrados: 0
Puntos de ruido: 39644 (100.0%)
Tiempo: 3.51s
Distribución:
  Ruido: 39644

In [30]:
# Ejemplo iteración 1: eps=0.25, min_samples=3
k_eps = 1
k_min = 15

start = time.time()
db = DBSCAN(eps=k_eps, min_samples=k_min)
labels = db.fit_predict(X_scaled)
end = time.time()

n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_ruido = list(labels).count(-1)
distribucion = pd.Series(labels).value_counts().sort_index()

resultados_dbscan[(k_eps, k_min)] = labels

print(f"Iteración | eps={k_eps} | MinPts={k_min}")
print(f"Clusters encontrados: {n_clusters}")
print(f"Puntos de ruido: {n_ruido} ({n_ruido/len(labels)*100:.1f}%)")
print(f"Tiempo: {end-start:.2f}s")
print(f"Distribución:")
for grupo, cantidad in distribucion.items():
    nombre = "Ruido" if grupo == -1 else f"G{grupo+1}"
    print(f"  {nombre}: {cantidad}")

Iteración | eps=1 | MinPts=15
Clusters encontrados: 0
Puntos de ruido: 39644 (100.0%)
Tiempo: 3.58s
Distribución:
  Ruido: 39644

In [31]:
# Ejemplo iteración 1: eps=0.25, min_samples=3
k_eps = 2.5
k_min = 23

start = time.time()
db = DBSCAN(eps=k_eps, min_samples=k_min)
labels = db.fit_predict(X_scaled)
end = time.time()

n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_ruido = list(labels).count(-1)
distribucion = pd.Series(labels).value_counts().sort_index()

resultados_dbscan[(k_eps, k_min)] = labels

print(f"Iteración | eps={k_eps} | MinPts={k_min}")
print(f"Clusters encontrados: {n_clusters}")
print(f"Puntos de ruido: {n_ruido} ({n_ruido/len(labels)*100:.1f}%)")
print(f"Tiempo: {end-start:.2f}s")
print(f"Distribución:")
for grupo, cantidad in distribucion.items():
    nombre = "Ruido" if grupo == -1 else f"G{grupo+1}"
    print(f"  {nombre}: {cantidad}")

Iteración | eps=2.5 | MinPts=23
Clusters encontrados: 12
Puntos de ruido: 39099 (98.6%)
Tiempo: 3.78s
Distribución:
  Ruido: 39099
  G1: 77
  G2: 65
  G3: 103
  G4: 23
  G5: 66
  G6: 34
  G7: 28
  G8: 23
  G9: 28
  G10: 38
  G11: 37
  G12: 23

In [32]:
# Ejemplo iteración 1: eps=0.25, min_samples=3
k_eps = 5
k_min = 41

start = time.time()
db = DBSCAN(eps=k_eps, min_samples=k_min)
labels = db.fit_predict(X_scaled)
end = time.time()

n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_ruido = list(labels).count(-1)
distribucion = pd.Series(labels).value_counts().sort_index()

resultados_dbscan[(k_eps, k_min)] = labels

print(f"Iteración | eps={k_eps} | MinPts={k_min}")
print(f"Clusters encontrados: {n_clusters}")
print(f"Puntos de ruido: {n_ruido} ({n_ruido/len(labels)*100:.1f}%)")
print(f"Tiempo: {end-start:.2f}s")
print(f"Distribución:")
for grupo, cantidad in distribucion.items():
    nombre = "Ruido" if grupo == -1 else f"G{grupo+1}"
    print(f"  {nombre}: {cantidad}")

Iteración | eps=5 | MinPts=41
Clusters encontrados: 11
Puntos de ruido: 6001 (15.1%)
Tiempo: 4.03s
Distribución:
  Ruido: 6001
  G1: 26391
  G2: 1373
  G3: 1713
  G4: 1551
  G5: 1260
  G6: 933
  G7: 48
  G8: 72
  G9: 141
  G10: 57
  G11: 104

In [33]:
from sklearn.cluster import DBSCAN
import pandas as pd
import time

epsilons = [round(i * 0.25, 2) for i in range(1, 21)]
minpts_vals = [i * 2 + 1 for i in range(1, 21)]

resultados_dbscan = []
total = len(epsilons) * len(minpts_vals)
iteracion = 1

print(f"Iniciando {total} iteraciones de DBSCAN...")
print("="*70)

for eps in epsilons:
    for min_pts in minpts_vals:
        start = time.time()
        db = DBSCAN(eps=eps, min_samples=min_pts)
        labels = db.fit_predict(X_scaled)
        end = time.time()

        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
        n_ruido = list(labels).count(-1)
        pct_ruido = round(n_ruido / len(labels) * 100, 2)

        distribucion = pd.Series(labels).value_counts().sort_index()
        grupos = {f"G{g+1}" if g != -1 else "Ruido": int(c) 
                  for g, c in distribucion.items()}

        resultados_dbscan.append({
            "Iteracion": iteracion,
            "Epsilon": eps,
            "MinPts": min_pts,
            "N_Clusters": n_clusters,
            "N_Ruido": n_ruido,
            "Pct_Ruido": pct_ruido,
            "Tiempo_s": round(end - start, 2),
            **grupos
        })

        print(f"[{iteracion:>3}/{total}] eps={eps:.2f} | MinPts={min_pts:>2} | "
              f"Clusters={n_clusters:>3} | Ruido={pct_ruido:>6.2f}% | "
              f"Tiempo={end-start:.1f}s")

        iteracion += 1

df_resultados = pd.DataFrame(resultados_dbscan)
df_resultados.to_csv("resultados_dbscan.csv", index=False)
print("\n" + "="*70)
print("COMPLETADO. Resultados guardados en 'resultados_dbscan.csv'")
print(f"Total iteraciones: {len(df_resultados)}")
print("\nResumen:")
print(f"  Iteraciones con 0 clusters (todo ruido): {(df_resultados['N_Clusters']==0).sum()}")
print(f"  Iteraciones con 2-10 clusters: {((df_resultados['N_Clusters']>=2) & (df_resultados['N_Clusters']<=10)).sum()}")
print(f"  Iteraciones con >10 clusters: {(df_resultados['N_Clusters']>10).sum()}")
print("\nMejores combinaciones (2-10 clusters, ruido < 30%):")
mejores = df_resultados[
    (df_resultados['N_Clusters'] >= 2) & 
    (df_resultados['N_Clusters'] <= 10) & 
    (df_resultados['Pct_Ruido'] < 30)
][['Iteracion','Epsilon','MinPts','N_Clusters','Pct_Ruido']].head(20)
print(mejores.to_string(index=False) if len(mejores) > 0 else "  Ninguna encontrada aún, prueba rangos más amplios")

Iniciando 400 iteraciones de DBSCAN...
======================================================================
[  1/400] eps=0.25 | MinPts= 3 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[  2/400] eps=0.25 | MinPts= 5 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[  3/400] eps=0.25 | MinPts= 7 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[  4/400] eps=0.25 | MinPts= 9 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[  5/400] eps=0.25 | MinPts=11 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[  6/400] eps=0.25 | MinPts=13 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[  7/400] eps=0.25 | MinPts=15 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[  8/400] eps=0.25 | MinPts=17 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[  9/400] eps=0.25 | MinPts=19 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 10/400] eps=0.25 | MinPts=21 | Clusters=  0 | Ruido=100.00% | Tiempo=3.6s
[ 11/400] eps=0.25 | MinPts=23 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 12/400] eps=0.25 | MinPts=25 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 13/400] eps=0.25 | MinPts=27 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 14/400] eps=0.25 | MinPts=29 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 15/400] eps=0.25 | MinPts=31 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 16/400] eps=0.25 | MinPts=33 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 17/400] eps=0.25 | MinPts=35 | Clusters=  0 | Ruido=100.00% | Tiempo=3.7s
[ 18/400] eps=0.25 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 19/400] eps=0.25 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 20/400] eps=0.25 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 21/400] eps=0.50 | MinPts= 3 | Clusters=  1 | Ruido= 99.99% | Tiempo=3.4s
[ 22/400] eps=0.50 | MinPts= 5 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 23/400] eps=0.50 | MinPts= 7 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 24/400] eps=0.50 | MinPts= 9 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 25/400] eps=0.50 | MinPts=11 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 26/400] eps=0.50 | MinPts=13 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 27/400] eps=0.50 | MinPts=15 | Clusters=  0 | Ruido=100.00% | Tiempo=3.7s
[ 28/400] eps=0.50 | MinPts=17 | Clusters=  0 | Ruido=100.00% | Tiempo=3.6s
[ 29/400] eps=0.50 | MinPts=19 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 30/400] eps=0.50 | MinPts=21 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 31/400] eps=0.50 | MinPts=23 | Clusters=  0 | Ruido=100.00% | Tiempo=3.2s
[ 32/400] eps=0.50 | MinPts=25 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 33/400] eps=0.50 | MinPts=27 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 34/400] eps=0.50 | MinPts=29 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 35/400] eps=0.50 | MinPts=31 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 36/400] eps=0.50 | MinPts=33 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 37/400] eps=0.50 | MinPts=35 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 38/400] eps=0.50 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 39/400] eps=0.50 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 40/400] eps=0.50 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 41/400] eps=0.75 | MinPts= 3 | Clusters=  2 | Ruido= 99.98% | Tiempo=3.5s
[ 42/400] eps=0.75 | MinPts= 5 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 43/400] eps=0.75 | MinPts= 7 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 44/400] eps=0.75 | MinPts= 9 | Clusters=  0 | Ruido=100.00% | Tiempo=3.6s
[ 45/400] eps=0.75 | MinPts=11 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 46/400] eps=0.75 | MinPts=13 | Clusters=  0 | Ruido=100.00% | Tiempo=3.6s
[ 47/400] eps=0.75 | MinPts=15 | Clusters=  0 | Ruido=100.00% | Tiempo=3.6s
[ 48/400] eps=0.75 | MinPts=17 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 49/400] eps=0.75 | MinPts=19 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 50/400] eps=0.75 | MinPts=21 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 51/400] eps=0.75 | MinPts=23 | Clusters=  0 | Ruido=100.00% | Tiempo=3.2s
[ 52/400] eps=0.75 | MinPts=25 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 53/400] eps=0.75 | MinPts=27 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 54/400] eps=0.75 | MinPts=29 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 55/400] eps=0.75 | MinPts=31 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 56/400] eps=0.75 | MinPts=33 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 57/400] eps=0.75 | MinPts=35 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 58/400] eps=0.75 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=3.6s
[ 59/400] eps=0.75 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 60/400] eps=0.75 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 61/400] eps=1.00 | MinPts= 3 | Clusters= 14 | Ruido= 99.87% | Tiempo=3.5s
[ 62/400] eps=1.00 | MinPts= 5 | Clusters=  1 | Ruido= 99.99% | Tiempo=3.3s
[ 63/400] eps=1.00 | MinPts= 7 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 64/400] eps=1.00 | MinPts= 9 | Clusters=  0 | Ruido=100.00% | Tiempo=3.6s
[ 65/400] eps=1.00 | MinPts=11 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[ 66/400] eps=1.00 | MinPts=13 | Clusters=  0 | Ruido=100.00% | Tiempo=3.7s
[ 67/400] eps=1.00 | MinPts=15 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 68/400] eps=1.00 | MinPts=17 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 69/400] eps=1.00 | MinPts=19 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 70/400] eps=1.00 | MinPts=21 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 71/400] eps=1.00 | MinPts=23 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 72/400] eps=1.00 | MinPts=25 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 73/400] eps=1.00 | MinPts=27 | Clusters=  0 | Ruido=100.00% | Tiempo=3.5s
[ 74/400] eps=1.00 | MinPts=29 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 75/400] eps=1.00 | MinPts=31 | Clusters=  0 | Ruido=100.00% | Tiempo=3.3s
[ 76/400] eps=1.00 | MinPts=33 | Clusters=  0 | Ruido=100.00% | Tiempo=3.4s
[ 77/400] eps=1.00 | MinPts=35 | Clusters=  0 | Ruido=100.00% | Tiempo=4.7s
[ 78/400] eps=1.00 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[ 79/400] eps=1.00 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[ 80/400] eps=1.00 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[ 81/400] eps=1.25 | MinPts= 3 | Clusters= 25 | Ruido= 99.65% | Tiempo=4.1s
[ 82/400] eps=1.25 | MinPts= 5 | Clusters=  8 | Ruido= 99.85% | Tiempo=3.9s
[ 83/400] eps=1.25 | MinPts= 7 | Clusters=  3 | Ruido= 99.94% | Tiempo=3.9s
[ 84/400] eps=1.25 | MinPts= 9 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[ 85/400] eps=1.25 | MinPts=11 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[ 86/400] eps=1.25 | MinPts=13 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[ 87/400] eps=1.25 | MinPts=15 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[ 88/400] eps=1.25 | MinPts=17 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[ 89/400] eps=1.25 | MinPts=19 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[ 90/400] eps=1.25 | MinPts=21 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[ 91/400] eps=1.25 | MinPts=23 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[ 92/400] eps=1.25 | MinPts=25 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[ 93/400] eps=1.25 | MinPts=27 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[ 94/400] eps=1.25 | MinPts=29 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[ 95/400] eps=1.25 | MinPts=31 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[ 96/400] eps=1.25 | MinPts=33 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[ 97/400] eps=1.25 | MinPts=35 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[ 98/400] eps=1.25 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[ 99/400] eps=1.25 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[100/400] eps=1.25 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[101/400] eps=1.50 | MinPts= 3 | Clusters= 48 | Ruido= 99.28% | Tiempo=4.4s
[102/400] eps=1.50 | MinPts= 5 | Clusters= 12 | Ruido= 99.66% | Tiempo=3.9s
[103/400] eps=1.50 | MinPts= 7 | Clusters=  7 | Ruido= 99.79% | Tiempo=4.0s
[104/400] eps=1.50 | MinPts= 9 | Clusters=  3 | Ruido= 99.90% | Tiempo=3.9s
[105/400] eps=1.50 | MinPts=11 | Clusters=  2 | Ruido= 99.94% | Tiempo=3.9s
[106/400] eps=1.50 | MinPts=13 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[107/400] eps=1.50 | MinPts=15 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[108/400] eps=1.50 | MinPts=17 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[109/400] eps=1.50 | MinPts=19 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[110/400] eps=1.50 | MinPts=21 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[111/400] eps=1.50 | MinPts=23 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[112/400] eps=1.50 | MinPts=25 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[113/400] eps=1.50 | MinPts=27 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[114/400] eps=1.50 | MinPts=29 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[115/400] eps=1.50 | MinPts=31 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[116/400] eps=1.50 | MinPts=33 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[117/400] eps=1.50 | MinPts=35 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[118/400] eps=1.50 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[119/400] eps=1.50 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[120/400] eps=1.50 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=4.3s
[121/400] eps=1.75 | MinPts= 3 | Clusters= 87 | Ruido= 98.51% | Tiempo=4.3s
[122/400] eps=1.75 | MinPts= 5 | Clusters= 28 | Ruido= 99.21% | Tiempo=3.9s
[123/400] eps=1.75 | MinPts= 7 | Clusters= 11 | Ruido= 99.55% | Tiempo=3.9s
[124/400] eps=1.75 | MinPts= 9 | Clusters=  7 | Ruido= 99.69% | Tiempo=4.2s
[125/400] eps=1.75 | MinPts=11 | Clusters=  5 | Ruido= 99.81% | Tiempo=4.0s
[126/400] eps=1.75 | MinPts=13 | Clusters=  2 | Ruido= 99.91% | Tiempo=4.0s
[127/400] eps=1.75 | MinPts=15 | Clusters=  1 | Ruido= 99.94% | Tiempo=3.9s
[128/400] eps=1.75 | MinPts=17 | Clusters=  1 | Ruido= 99.96% | Tiempo=4.1s
[129/400] eps=1.75 | MinPts=19 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[130/400] eps=1.75 | MinPts=21 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[131/400] eps=1.75 | MinPts=23 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[132/400] eps=1.75 | MinPts=25 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[133/400] eps=1.75 | MinPts=27 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[134/400] eps=1.75 | MinPts=29 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[135/400] eps=1.75 | MinPts=31 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[136/400] eps=1.75 | MinPts=33 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[137/400] eps=1.75 | MinPts=35 | Clusters=  0 | Ruido=100.00% | Tiempo=4.2s
[138/400] eps=1.75 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[139/400] eps=1.75 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[140/400] eps=1.75 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[141/400] eps=2.00 | MinPts= 3 | Clusters=192 | Ruido= 96.84% | Tiempo=3.7s
[142/400] eps=2.00 | MinPts= 5 | Clusters= 58 | Ruido= 98.35% | Tiempo=3.9s
[143/400] eps=2.00 | MinPts= 7 | Clusters= 22 | Ruido= 98.99% | Tiempo=4.0s
[144/400] eps=2.00 | MinPts= 9 | Clusters= 12 | Ruido= 99.30% | Tiempo=4.0s
[145/400] eps=2.00 | MinPts=11 | Clusters=  8 | Ruido= 99.51% | Tiempo=3.9s
[146/400] eps=2.00 | MinPts=13 | Clusters=  6 | Ruido= 99.62% | Tiempo=4.1s
[147/400] eps=2.00 | MinPts=15 | Clusters=  4 | Ruido= 99.73% | Tiempo=3.9s
[148/400] eps=2.00 | MinPts=17 | Clusters=  2 | Ruido= 99.85% | Tiempo=3.8s
[149/400] eps=2.00 | MinPts=19 | Clusters=  1 | Ruido= 99.91% | Tiempo=4.1s
[150/400] eps=2.00 | MinPts=21 | Clusters=  1 | Ruido= 99.94% | Tiempo=4.0s
[151/400] eps=2.00 | MinPts=23 | Clusters=  1 | Ruido= 99.94% | Tiempo=3.9s
[152/400] eps=2.00 | MinPts=25 | Clusters=  0 | Ruido=100.00% | Tiempo=4.4s
[153/400] eps=2.00 | MinPts=27 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[154/400] eps=2.00 | MinPts=29 | Clusters=  0 | Ruido=100.00% | Tiempo=4.5s
[155/400] eps=2.00 | MinPts=31 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[156/400] eps=2.00 | MinPts=33 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[157/400] eps=2.00 | MinPts=35 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[158/400] eps=2.00 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[159/400] eps=2.00 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[160/400] eps=2.00 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[161/400] eps=2.25 | MinPts= 3 | Clusters=343 | Ruido= 92.39% | Tiempo=3.9s
[162/400] eps=2.25 | MinPts= 5 | Clusters=112 | Ruido= 95.70% | Tiempo=3.8s
[163/400] eps=2.25 | MinPts= 7 | Clusters= 67 | Ruido= 97.28% | Tiempo=4.1s
[164/400] eps=2.25 | MinPts= 9 | Clusters= 33 | Ruido= 98.30% | Tiempo=4.0s
[165/400] eps=2.25 | MinPts=11 | Clusters= 19 | Ruido= 98.85% | Tiempo=3.8s
[166/400] eps=2.25 | MinPts=13 | Clusters= 12 | Ruido= 99.19% | Tiempo=3.9s
[167/400] eps=2.25 | MinPts=15 | Clusters=  8 | Ruido= 99.35% | Tiempo=4.0s
[168/400] eps=2.25 | MinPts=17 | Clusters=  7 | Ruido= 99.49% | Tiempo=3.9s
[169/400] eps=2.25 | MinPts=19 | Clusters=  5 | Ruido= 99.63% | Tiempo=3.7s
[170/400] eps=2.25 | MinPts=21 | Clusters=  2 | Ruido= 99.82% | Tiempo=4.0s
[171/400] eps=2.25 | MinPts=23 | Clusters=  1 | Ruido= 99.89% | Tiempo=3.9s
[172/400] eps=2.25 | MinPts=25 | Clusters=  1 | Ruido= 99.89% | Tiempo=4.2s
[173/400] eps=2.25 | MinPts=27 | Clusters=  1 | Ruido= 99.90% | Tiempo=3.8s
[174/400] eps=2.25 | MinPts=29 | Clusters=  1 | Ruido= 99.90% | Tiempo=3.9s
[175/400] eps=2.25 | MinPts=31 | Clusters=  1 | Ruido= 99.92% | Tiempo=4.0s
[176/400] eps=2.25 | MinPts=33 | Clusters=  0 | Ruido=100.00% | Tiempo=4.5s
[177/400] eps=2.25 | MinPts=35 | Clusters=  0 | Ruido=100.00% | Tiempo=3.8s
[178/400] eps=2.25 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[179/400] eps=2.25 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=3.9s
[180/400] eps=2.25 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=4.1s
[181/400] eps=2.50 | MinPts= 3 | Clusters=411 | Ruido= 84.06% | Tiempo=3.8s
[182/400] eps=2.50 | MinPts= 5 | Clusters=151 | Ruido= 88.99% | Tiempo=3.9s
[183/400] eps=2.50 | MinPts= 7 | Clusters= 79 | Ruido= 91.67% | Tiempo=3.9s
[184/400] eps=2.50 | MinPts= 9 | Clusters= 57 | Ruido= 93.36% | Tiempo=3.9s
[185/400] eps=2.50 | MinPts=11 | Clusters= 45 | Ruido= 94.72% | Tiempo=3.8s
[186/400] eps=2.50 | MinPts=13 | Clusters= 36 | Ruido= 95.74% | Tiempo=3.8s
[187/400] eps=2.50 | MinPts=15 | Clusters= 26 | Ruido= 96.74% | Tiempo=4.0s
[188/400] eps=2.50 | MinPts=17 | Clusters= 19 | Ruido= 97.54% | Tiempo=3.9s
[189/400] eps=2.50 | MinPts=19 | Clusters= 15 | Ruido= 98.07% | Tiempo=3.8s
[190/400] eps=2.50 | MinPts=21 | Clusters= 12 | Ruido= 98.49% | Tiempo=3.9s
[191/400] eps=2.50 | MinPts=23 | Clusters= 12 | Ruido= 98.63% | Tiempo=4.1s
[192/400] eps=2.50 | MinPts=25 | Clusters=  7 | Ruido= 99.18% | Tiempo=4.0s
[193/400] eps=2.50 | MinPts=27 | Clusters=  6 | Ruido= 99.31% | Tiempo=3.8s
[194/400] eps=2.50 | MinPts=29 | Clusters=  3 | Ruido= 99.57% | Tiempo=4.0s
[195/400] eps=2.50 | MinPts=31 | Clusters=  2 | Ruido= 99.68% | Tiempo=3.8s
[196/400] eps=2.50 | MinPts=33 | Clusters=  2 | Ruido= 99.79% | Tiempo=3.9s
[197/400] eps=2.50 | MinPts=35 | Clusters=  1 | Ruido= 99.88% | Tiempo=3.9s
[198/400] eps=2.50 | MinPts=37 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[199/400] eps=2.50 | MinPts=39 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[200/400] eps=2.50 | MinPts=41 | Clusters=  0 | Ruido=100.00% | Tiempo=4.0s
[201/400] eps=2.75 | MinPts= 3 | Clusters=492 | Ruido= 73.05% | Tiempo=4.0s
[202/400] eps=2.75 | MinPts= 5 | Clusters=160 | Ruido= 78.80% | Tiempo=4.1s
[203/400] eps=2.75 | MinPts= 7 | Clusters= 99 | Ruido= 82.02% | Tiempo=4.0s
[204/400] eps=2.75 | MinPts= 9 | Clusters= 75 | Ruido= 84.16% | Tiempo=4.0s
[205/400] eps=2.75 | MinPts=11 | Clusters= 55 | Ruido= 86.19% | Tiempo=3.9s
[206/400] eps=2.75 | MinPts=13 | Clusters= 49 | Ruido= 87.78% | Tiempo=4.0s
[207/400] eps=2.75 | MinPts=15 | Clusters= 41 | Ruido= 89.07% | Tiempo=4.0s
[208/400] eps=2.75 | MinPts=17 | Clusters= 36 | Ruido= 90.33% | Tiempo=4.0s
[209/400] eps=2.75 | MinPts=19 | Clusters= 33 | Ruido= 91.30% | Tiempo=3.9s
[210/400] eps=2.75 | MinPts=21 | Clusters= 29 | Ruido= 92.04% | Tiempo=3.9s
[211/400] eps=2.75 | MinPts=23 | Clusters= 24 | Ruido= 93.00% | Tiempo=4.3s
[212/400] eps=2.75 | MinPts=25 | Clusters= 20 | Ruido= 93.81% | Tiempo=4.0s
[213/400] eps=2.75 | MinPts=27 | Clusters= 18 | Ruido= 94.49% | Tiempo=5.7s
[214/400] eps=2.75 | MinPts=29 | Clusters= 16 | Ruido= 95.11% | Tiempo=8.7s
[215/400] eps=2.75 | MinPts=31 | Clusters= 14 | Ruido= 95.55% | Tiempo=8.6s
[216/400] eps=2.75 | MinPts=33 | Clusters= 12 | Ruido= 96.05% | Tiempo=8.5s
[217/400] eps=2.75 | MinPts=35 | Clusters=  9 | Ruido= 96.45% | Tiempo=8.5s
[218/400] eps=2.75 | MinPts=37 | Clusters=  9 | Ruido= 96.76% | Tiempo=8.1s
[219/400] eps=2.75 | MinPts=39 | Clusters=  8 | Ruido= 97.13% | Tiempo=4.9s
[220/400] eps=2.75 | MinPts=41 | Clusters=  7 | Ruido= 97.59% | Tiempo=4.3s
[221/400] eps=3.00 | MinPts= 3 | Clusters=542 | Ruido= 61.28% | Tiempo=4.6s
[222/400] eps=3.00 | MinPts= 5 | Clusters=175 | Ruido= 67.66% | Tiempo=4.4s
[223/400] eps=3.00 | MinPts= 7 | Clusters=117 | Ruido= 71.08% | Tiempo=4.9s
[224/400] eps=3.00 | MinPts= 9 | Clusters= 85 | Ruido= 73.69% | Tiempo=4.5s
[225/400] eps=3.00 | MinPts=11 | Clusters= 66 | Ruido= 75.72% | Tiempo=4.7s
[226/400] eps=3.00 | MinPts=13 | Clusters= 54 | Ruido= 77.38% | Tiempo=4.7s
[227/400] eps=3.00 | MinPts=15 | Clusters= 48 | Ruido= 78.76% | Tiempo=4.5s
[228/400] eps=3.00 | MinPts=17 | Clusters= 43 | Ruido= 80.00% | Tiempo=4.4s
[229/400] eps=3.00 | MinPts=19 | Clusters= 36 | Ruido= 81.48% | Tiempo=4.4s
[230/400] eps=3.00 | MinPts=21 | Clusters= 35 | Ruido= 82.50% | Tiempo=4.7s
[231/400] eps=3.00 | MinPts=23 | Clusters= 33 | Ruido= 83.58% | Tiempo=4.9s
[232/400] eps=3.00 | MinPts=25 | Clusters= 30 | Ruido= 84.51% | Tiempo=4.5s
[233/400] eps=3.00 | MinPts=27 | Clusters= 29 | Ruido= 85.16% | Tiempo=4.4s
[234/400] eps=3.00 | MinPts=29 | Clusters= 28 | Ruido= 85.91% | Tiempo=4.2s
[235/400] eps=3.00 | MinPts=31 | Clusters= 26 | Ruido= 86.78% | Tiempo=4.4s
[236/400] eps=3.00 | MinPts=33 | Clusters= 25 | Ruido= 87.53% | Tiempo=4.3s
[237/400] eps=3.00 | MinPts=35 | Clusters= 24 | Ruido= 88.22% | Tiempo=4.3s
[238/400] eps=3.00 | MinPts=37 | Clusters= 24 | Ruido= 88.89% | Tiempo=4.6s
[239/400] eps=3.00 | MinPts=39 | Clusters= 20 | Ruido= 90.05% | Tiempo=4.7s
[240/400] eps=3.00 | MinPts=41 | Clusters= 18 | Ruido= 90.61% | Tiempo=4.1s
[241/400] eps=3.25 | MinPts= 3 | Clusters=504 | Ruido= 49.73% | Tiempo=4.1s
[242/400] eps=3.25 | MinPts= 5 | Clusters=198 | Ruido= 55.89% | Tiempo=4.4s
[243/400] eps=3.25 | MinPts= 7 | Clusters=134 | Ruido= 59.80% | Tiempo=4.0s
[244/400] eps=3.25 | MinPts= 9 | Clusters= 92 | Ruido= 62.58% | Tiempo=3.9s
[245/400] eps=3.25 | MinPts=11 | Clusters= 78 | Ruido= 64.58% | Tiempo=4.0s
[246/400] eps=3.25 | MinPts=13 | Clusters= 66 | Ruido= 66.52% | Tiempo=4.0s
[247/400] eps=3.25 | MinPts=15 | Clusters= 57 | Ruido= 67.99% | Tiempo=4.3s
[248/400] eps=3.25 | MinPts=17 | Clusters= 52 | Ruido= 69.25% | Tiempo=4.0s
[249/400] eps=3.25 | MinPts=19 | Clusters= 47 | Ruido= 70.50% | Tiempo=4.1s
[250/400] eps=3.25 | MinPts=21 | Clusters= 43 | Ruido= 71.52% | Tiempo=4.0s
[251/400] eps=3.25 | MinPts=23 | Clusters= 38 | Ruido= 72.61% | Tiempo=4.0s
[252/400] eps=3.25 | MinPts=25 | Clusters= 35 | Ruido= 73.47% | Tiempo=3.8s
[253/400] eps=3.25 | MinPts=27 | Clusters= 37 | Ruido= 74.18% | Tiempo=4.2s
[254/400] eps=3.25 | MinPts=29 | Clusters= 31 | Ruido= 75.35% | Tiempo=4.3s
[255/400] eps=3.25 | MinPts=31 | Clusters= 28 | Ruido= 76.15% | Tiempo=4.3s
[256/400] eps=3.25 | MinPts=33 | Clusters= 28 | Ruido= 76.73% | Tiempo=4.0s
[257/400] eps=3.25 | MinPts=35 | Clusters= 26 | Ruido= 77.34% | Tiempo=5.0s
[258/400] eps=3.25 | MinPts=37 | Clusters= 27 | Ruido= 78.15% | Tiempo=4.1s
[259/400] eps=3.25 | MinPts=39 | Clusters= 26 | Ruido= 78.83% | Tiempo=4.0s
[260/400] eps=3.25 | MinPts=41 | Clusters= 25 | Ruido= 79.68% | Tiempo=3.9s
[261/400] eps=3.50 | MinPts= 3 | Clusters=428 | Ruido= 39.42% | Tiempo=4.3s